name: 'Notify Parent'

on:
  push:
    branches:
      - main    

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  notify:
    name: 'Submodule Notify Parent'
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Github REST API Call
      run: |
        curl \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/torbet/Site-2/actions/workflows/Notify-Parent.yml/dispatches \
          -d '{"ref":"ref"}'
